---
- name: Enable NFS v3 related services
  service: name=rpcbind state=started enabled=yes
  when: nfs_mount.version | default(nfs_default_version) == 3

- name: Make sure mount point is present
  file: path={{nfs_mount.mount_point | default(nfs_default_mount_point)}} state=directory owner=root group=root mode=0755

- name: Mount exported filesystem
  mount: name={{nfs_mount.mount_point | default(nfs_default_mount_point)}} src={{nfs_mount.server | default(nfs_default_server)}}:{{nfs_mount.export_dir | default(nfs_default_export_dir)}} fstype=nfs opts={{nfs_mount.mount_opts | default(nfs_default_mount_opts)}},vers={{nfs_mount.version | default(nfs_default_version)}} state=mounted
