---
- name: Configure NFS
  template: dest=/etc/sysconfig/nfs src=sysconfig.j2 owner=root group=root mode=0644
  notify:
    - Restart rpcbind
    - Restart nfs
    - Restart nfslock

- name: Enable NFS related services
  service: name={{item}} state=started enabled=yes
  with_items:
    - rpcbind
    - nfs-server
    - nfslock

- name: Ensure NFS export is present
  file: path={{export.export_dir | default(nfs_default_export_dir)}} state=directory mode={{export.export_mode | default(nfs_default_export_mode)}} owner={{export.export_user | default(nfs_default_export_user)}} group={{export.export_group | default(nfs_default_export_group)}} recurse=no

- name: Ensure exports.d is present
  file: path=/etc/exports.d state=directory owner=root group=root mode=0755

- name: Export to clients
  template: dest=/etc/exports.d/{{export.name | default(nfs_default_name)}}.exports src=exports.j2 owner=root group=root mode=0644
  notify:
    - Reload exports
